name: app-prod
services:
  database:
    container_name: app-database
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=teste
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 30s
      timeout: 10s
      retries: 5

  web:
    container_name: app-web
    restart: always
    env_file:
      - .env.prod
    build:
      context: ./
      dockerfile: prod.Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        NODE_ENV: ${NODE_ENV}
    ports:
      - 80:3000
    depends_on:
      database:
        condition: service_healthy
        restart: true
        
# Se você quiser usar uma base de dados diferente da de produção, alterar a propriedade name do volume aqui 
volumes:
  db-data:
    name: "app-database"
    external: true

# Você pode especificar um arquivo de senha diferente para cada ambiente
secrets:
  db-password:
    file: ./db/password.txt